### ISSUE TITLE
ServiceProxy中存在隐患

### ISSUE THREAD

**Issue by 543211494** [liyupi/yu-rpc#7]
method.getDeclaringClass().getName()获取的是接口的完整路径
如果服务端和客户端定义的接口放在不同路径会导致无法调用
应将不含路径的接口名注册到LocalRegistry

**Comment by liyupi** [comment]
是的，虽然实际开发中一般直接引入接口和公共模块，但确实存在这个隐患，由于涉及的改动点可能不止一处，暂时在代码中通过 fixme 注释标识。不影响学习，有时间的小伙伴可自行优化
